# Generated by Django 5.0.6 on 2024-06-14 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_storage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmaterial',
            old_name='material_id',
            new_name='material',
        ),
        migrations.RenameField(
            model_name='productmaterial',
            old_name='product_id',
            new_name='product',
        ),
    ]
