# Generated by Django 5.0.6 on 2024-06-14 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_material_id_storage_material'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Storage',
            new_name='Warehouse',
        ),
    ]
